### ISSUE TITLE
Can't save in psd

### ISSUE THREAD

**Issue by brunosly** [loonghao/photoshop_python_api#14]
Hello. I did a little script that save's every layer as an png file, but I would like to make it able to save in PSD.

I tried using PhotoshopSaveOptions instead of PNGSaveOptions but it just return some errors.

This is my working PNG code.

```
import photoshop as ps
import os

def main():
    app = ps.Application()
    doc = app.activeDocument()
    i = 0
    for y in doc.artLayers:
        j = 0
        for x in doc.artLayers:
            if i == j:
                x.visible = True
            else:
                x.visible = False
            j = j + 1
        i = i+1
        options = ps.PNGSaveOptions()
        if not os.path.exists(doc.path + '/' + y.name):
            os.mkdir(doc.path + '/' + y.name)
        imagepath = doc.path + '/' + y.name + '/' + y.name + '.png'
        doc.saveAs(imagepath, options, True)
    app.doJavaScript(f'alert("Task done!")')
    print(doc.activeLayer)

if __name__ == '__main__':
    main()`
```

If I use ps.PhotoshopSaveOptions() instead of ps.PNGSaveOptions() it will give this error.

> Traceback (most recent call last):
>   File "C:/Users/bruno.freitas/Desktop/PhotoshopLayer/Main.py", line 26, in <module>
>     main()
>   File "C:/Users/bruno.freitas/Desktop/PhotoshopLayer/Main.py", line 17, in main
>     options = ps.PhotoshopSaveOptions()
> AttributeError: module 'photoshop' has no attribute 'PhotoshopSaveOptions'
> 
> Process finished with exit code 1
> 

And if I use ps.save_options.PhotoshopSaveOptions() instead of ps.PNGSaveOptions() it will give this error.

> Traceback (most recent call last):
>   File "C:/Users/bruno.freitas/Desktop/PhotoshopLayer/Main.py", line 26, in <module>
>     main()
>   File "C:/Users/bruno.freitas/Desktop/PhotoshopLayer/Main.py", line 21, in main
>     doc.saveAs(imagepath, options, True)
>   File "C:\Users\bruno.freitas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\lazybind.py", line 182, in caller
>     return self._comobj._invoke(descr.memid, descr.invkind, 0, *args)
>   File "C:\Users\bruno.freitas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\automation.py", line 728, in _invoke
>     self.__com_Invoke(memid, riid_null, lcid, invkind,
> _ctypes.COMError: (-2147220261, None, (None, None, None, 0, None))
> 
> Process finished with exit code 1

I'm new to Python and not a pro programmer, so there's a great possibility that I'm just doing something very wrong. Can someone help me

**Comment by loonghao** [comment]
Hi @brunosly,
Thank you for your report, I double-check the code missing the PhotoshopSaveOptions in the session,
I will fix this soon and add an example to show you how to save active documents psd.

**Comment by loonghao** [comment]
@brunosly I updated the code to fix this issue and in below have two examples may help you.
 - https://github.com/loonghao/photoshop_python_api/blob/master/examples/export_layers_as_png.py
- https://github.com/loonghao/photoshop_python_api/blob/master/examples/save_to_psd.py


Let me know if you have any other questions.
Cheers,
Hal

**Comment by brunosly** [comment]
Thanks! It works perfectly now!
Also great work on this API, it's amazing.

**Comment by loonghao** [comment]
@all-contributors please add brunosly for Bug reports.
