### ISSUE TITLE
How to install the Python IDLE for photoshop

### ISSUE THREAD

**Issue by jeffli678** [loonghao/photoshop_python_api#6]
Hi, thanks for your effort and this repo looks promising. 

I think I am missing something. This is a gif in the readme (https://camo.githubusercontent.com/0945ad4bd06a25d41c34c4b608344612fbebb86b/68747470733a2f2f692e696d6775722e636f6d2f323554727a62562e676966) and I see a Python IDLE drop-down menu. Is it part of this project? I install via pip but it is not showing up. I browsed the code and I do not find relevant code for it. Or it is another tool?

**Comment by loonghao** [comment]
Hi, @jeffli678 Thank you for your interest. Yes, the IDEA stuff is in [photoshop_python_integration](https://github.com/loonghao/photoshop_python_integration).
This just a beta version, you can download it and test. enjoy.
